version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting installation"
      - pip install ansible boto3 paramiko
      - ansible-galaxy collection install community.docker  # Install required collection
  
  build:
    commands:
      - echo "Starting build phase"
      - mkdir -p app
      - echo "Hello World" > app/test.txt
  
  post_build:
    commands:
      - echo "Starting post-build phase"
      
      # Create ansible config
      - |
        cat > ansible/ansible.cfg << 'EOL'
        [defaults]
        host_key_checking = False
        timeout = 30
        pipelining = True
        command_warnings = False
        deprecation_warnings = False
        
        [ssh_connection]
        retries = 3
        ssh_args = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        EOL
      
      # Use base64 encoded key
      - |
        echo "Decoding SSH key from base64..."
        echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > /tmp/private_key.pem
        chmod 600 /tmp/private_key.pem
        
        echo "Checking key file stats:"
        ls -la /tmp/private_key.pem
        
        echo "Validating key format:"
        if ssh-keygen -y -f /tmp/private_key.pem &>/dev/null; then
          echo "✅ Key is valid"
          echo "Public key: $(ssh-keygen -y -f /tmp/private_key.pem | head -n 1)"
        else
          echo "❌ Key is invalid or incorrectly formatted"
          echo "Key begins with: $(head -n 1 /tmp/private_key.pem)"
          echo "Key ends with: $(tail -n 1 /tmp/private_key.pem)"
          exit 1
        fi
      
      # Create dynamic inventory with the decoded key
      - |
        cat > ansible/dynamic_inventory.ini << EOL
        [cloudsecure_instances]
        $INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/private_key.pem
        
        [cloudsecure_instances:vars]
        ansible_python_interpreter=/usr/bin/python3
        ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        EOL
      
      # Run Ansible with the properly formatted key
      - |
        cd ansible
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i dynamic_inventory.ini deploy.yml -v

artifacts:
  files:
    - ansible/**/*
    - app/**/*
  discard-paths: no