version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting installation"
      - pip install ansible boto3 paramiko  # Add paramiko for SSH connection support
  
  build:
    commands:
      - echo "Starting build phase"
      - mkdir -p app
      - echo "Hello World" > app/test.txt
      # Build your application here as needed
  
  post_build:
    commands:
      - echo "Starting post-build phase"
      
      # Create ansible.cfg for automation
      - |
        cat > ansible/ansible.cfg << 'EOL'
        [defaults]
        host_key_checking = False
        timeout = 30
        pipelining = True
        command_warnings = False
        
        [ssh_connection]
        retries = 3
        EOL
      
      # Create dynamic inventory
      - echo "[cloudsecure_instances]" > ansible/dynamic_inventory.ini
      - echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/private_key.pem" >> ansible/dynamic_inventory.ini
      - echo "[cloudsecure_instances:vars]" >> ansible/dynamic_inventory.ini
      - echo "ansible_python_interpreter=/usr/bin/python3" >> ansible/dynamic_inventory.ini
      
      # Get SSH key and secure permissions
      - |
        aws secretsmanager get-secret-value --secret-id cloudsecure-ssh-key --query SecretString --output text > /tmp/private_key.pem
        chmod 600 /tmp/private_key.pem
        trap "rm -f /tmp/private_key.pem" EXIT
      
      # Run Ansible with proper error handling
      - |
        cd ansible
        if ansible-playbook -i dynamic_inventory.ini deploy.yml -v; then
          echo "Ansible deployment successful"
        else
          echo "Ansible deployment failed"
          exit 1
        fi

artifacts:
  files:
    - ansible/**/*
    - app/**/*
  discard-paths: no