version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies
      - yum update -y
      - amazon-linux-extras install docker -y
      - systemctl start docker || true
  
  build:
    commands:
      - echo Building the Docker images
      - cd app
      - docker-compose build
  
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - app/**/*
    - appspec.yml
