version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting installation"
      - pip install ansible boto3 paramiko
      - ansible-galaxy collection install community.docker  # Install required collection
  
  build:
    commands:
      - echo "Starting build phase"
      - mkdir -p app
      - echo "Hello World" > app/test.txt
  
  post_build:
    commands:
      - echo "Starting post-build phase"
      
      # Create ansible.cfg
      - |
        cat > ansible/ansible.cfg << 'EOL'
        [defaults]
        host_key_checking = False
        timeout = 30
        pipelining = True
        command_warnings = False
        
        [ssh_connection]
        retries = 3
        EOL
      
      # Create private key file from environment variable
      - |
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key.pem
        chmod 600 /tmp/private_key.pem
      
      # Create dynamic inventory with key authentication
      - |
        cat > ansible/dynamic_inventory.ini << EOL
        [cloudsecure_instances]
        $INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/private_key.pem
        
        [cloudsecure_instances:vars]
        ansible_python_interpreter=/usr/bin/python3
        EOL
      
      # Display inventory for debugging
      - cat ansible/dynamic_inventory.ini
      
      # Test SSH connectivity first
      - ansible cloudsecure_instances -i ansible/dynamic_inventory.ini -m ping -v
      
      # Run Ansible playbook
      - |
        cd ansible
        if ansible-playbook -i dynamic_inventory.ini deploy.yml -v; then
          echo "Ansible deployment successful"
        else
          echo "Ansible deployment failed"
          exit 1
        fi

artifacts:
  files:
    - ansible/**/*
    - app/**/*
  discard-paths: no