version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting installation"
      - pip install ansible boto3 paramiko
      - ansible-galaxy collection install community.docker  # Install required collection
  
  build:
    commands:
      - echo "Starting build phase"
      - mkdir -p app
      - echo "Hello World" > app/test.txt
  
  post_build:
    commands:
      - echo "Starting post-build phase"
      
      # Create ansible.cfg with more explicit settings
      - |
        cat > ansible/ansible.cfg << 'EOL'
        [defaults]
        host_key_checking = False
        timeout = 30
        pipelining = True
        command_warnings = False
        deprecation_warnings = False
        
        [ssh_connection]
        retries = 3
        ssh_args = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        EOL
      
      # Create SSH config file to disable host key checking
      - |
        mkdir -p ~/.ssh
        cat > ~/.ssh/config << 'EOL'
        Host *
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        EOL
        chmod 600 ~/.ssh/config
      
      # Create private key file
      - |
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key.pem
        chmod 600 /tmp/private_key.pem
      
      # Create dynamic inventory
      - |
        cat > ansible/dynamic_inventory.ini << EOL
        [cloudsecure_instances]
        $INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/private_key.pem
        
        [cloudsecure_instances:vars]
        ansible_python_interpreter=/usr/bin/python3
        ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        EOL
      
      # Test SSH connection directly first
      - |
        echo "Testing direct SSH connection..."
        ssh -i /tmp/private_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$INSTANCE_IP "echo SSH connection successful" || echo "SSH connection failed"
      
      # Run Ansible with additional options
      - |
        cd ansible
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i dynamic_inventory.ini deploy.yml -v

artifacts:
  files:
    - ansible/**/*
    - app/**/*
  discard-paths: no