version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting installation"
      - pip install ansible boto3 paramiko
      - ansible-galaxy collection install community.docker  # Install required collection
  
  build:
    commands:
      - echo "Starting build phase"
      - mkdir -p app
      - echo "Hello World" > app/test.txt
  
  post_build:
    commands:
      - echo "Starting post-build phase"
      
      # Create ansible.cfg
      - |
        cat > ansible/ansible.cfg << 'EOL'
        [defaults]
        host_key_checking = False
        timeout = 30
        pipelining = True
        command_warnings = False
        
        [ssh_connection]
        retries = 3
        EOL
      
      # Create dynamic inventory with key-based auth OR password-based auth
      - echo "[cloudsecure_instances]" > ansible/dynamic_inventory.ini
      
      # OPTION 1: Use password authentication instead of key-based auth
      - echo "$INSTANCE_IP ansible_user=ubuntu ansible_password=$EC2_PASSWORD" >> ansible/dynamic_inventory.ini
      
      # OPTION 2: If you still want to use key authentication, create a key file first
      # - |
      #   cat > /tmp/private_key.pem << 'EOL'
      #   -----BEGIN RSA PRIVATE KEY-----
      #   YOUR_PRIVATE_KEY_CONTENT_HERE
      #   -----END RSA PRIVATE KEY-----
      #   EOL
      #   chmod 600 /tmp/private_key.pem
      #   echo "$INSTANCE_IP ansible_user=ubuntu ansible_ssh_private_key_file=/tmp/private_key.pem" >> ansible/dynamic_inventory.ini
      
      - echo "[cloudsecure_instances:vars]" >> ansible/dynamic_inventory.ini
      - echo "ansible_python_interpreter=/usr/bin/python3" >> ansible/dynamic_inventory.ini
      
      # Run Ansible with proper error handling
      - |
        cd ansible
        if ansible-playbook -i dynamic_inventory.ini deploy.yml -v; then
          echo "Ansible deployment successful"
        else
          echo "Ansible deployment failed"
          exit 1
        fi

artifacts:
  files:
    - ansible/**/*
    - app/**/*
  discard-paths: no