version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Starting installation"
  
  build:
    commands:
      - echo "Starting build phase"
      - mkdir -p scripts
      - echo "Hello World" > test.txt
  
  post_build:
    commands:
      - echo "Starting post-build phase"
      # Create simplified deployment script
      - |
        cat > scripts/deploy.sh << 'EOL'
        #!/bin/bash
        echo "Deployment started"
        echo "Deployment completed"
        EOL
      - chmod +x scripts/deploy.sh
      
      # Create simplified installation script
      - |
        cat > scripts/before_install.sh << 'EOL'
        #!/bin/bash
        echo "Installation started"
        echo "Installation completed"
        mkdir -p /opt/security-ai/app
        EOL
      - chmod +x scripts/before_install.sh
      
      # Simplified appspec.yml
      - |
        cat > appspec.yml << 'EOL'
        version: 0.0
        os: linux
        files:
          - source: /test.txt
            destination: /opt/security-ai
          - source: /scripts
            destination: /opt/security-ai/scripts
        hooks:
          BeforeInstall:
            - location: scripts/before_install.sh
              timeout: 300
              runas: root
          ApplicationStart:
            - location: scripts/deploy.sh
              timeout: 300
              runas: root
        EOL

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - test.txt
  discard-paths: no