---
- name: Script-based CloudSecure Deployment
  hosts: cloudsecure_instances
  gather_facts: no
  
  tasks:
    - name: Create temporary directory
      raw: mkdir -p /tmp/.ansible-tmp && chmod 1777 /tmp/.ansible-tmp
      become: yes

    - name: Copy deployment script to server
      raw: echo '{{ lookup("file", "deploy_script.sh") }}' > /tmp/.ansible-tmp/deploy_script.sh && chmod +x /tmp/.ansible-tmp/deploy_script.sh
      become: yes
      
    - name: Run deployment script
      raw: sudo /tmp/.ansible-tmp/deploy_script.sh
      register: deploy_output
      
    - name: Show deployment output
      debug:
        var: deploy_output.stdout_lines