---
- name: Setup CloudSecure Environment
  hosts: cloudsecure_instances
  become: yes
  gather_facts: no
  
  vars:
    ansible_tmp_dir: "/tmp/.ansible-tmp"
    app_dir: /opt/cloudsecure
  
  tasks:
    - name: Ensure tmp directory exists
      raw: mkdir -p {{ ansible_tmp_dir }} && chmod 0777 {{ ansible_tmp_dir }}
      
    - name: Get Python version
      raw: python3 --version
      register: python_version
      
    - name: Show Python version
      debug:
        var: python_version.stdout_lines
        
    - name: Check OS details
      raw: cat /etc/os-release
      register: os_release
      
    - name: Debug OS info
      debug:
        var: os_release.stdout_lines
        
    - name: Create application directory
      raw: |
        mkdir -p {{ app_dir }} && 
        chmod 0755 {{ app_dir }} && 
        chown ec2-user:ec2-user {{ app_dir }}
        
    - name: Create test file
      raw: echo "Test successful!" > {{ app_dir }}/test.txt && chown ec2-user:ec2-user {{ app_dir }}/test.txt
      
    - name: Read test file
      raw: cat {{ app_dir }}/test.txt
      register: test_file
      
    - name: Show test file content
      debug:
        var: test_file.stdout_lines