---
- name: Test SSH connection and permissions
  hosts: cloudsecure_instances
  gather_facts: no
  
  tasks:
    - name: Get Python version
      raw: python3 --version
      register: python_version
      
    - name: Show Python version
      debug:
        var: python_version.stdout_lines
      
    - name: Test temp directory permissions (raw)
      raw: |
        mkdir -p /tmp/.ansible-tmp && 
        touch /tmp/.ansible-tmp/testfile && 
        ls -la /tmp/.ansible-tmp/testfile && 
        rm -rf /tmp/.ansible-tmp/testfile
      register: test_result
      
    - name: Show test result
      debug:
        var: test_result.stdout_lines