name: Minimal Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          if_key_exists: replace
      
      # Dynamically generate known_hosts
      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts
        
      # One-line deployment command with absolutely minimal syntax
      - name: Deploy with single command
        run: |
          ssh -o StrictHostKeyChecking=accept-new ${{ secrets.SSH_USERNAME }}@${{ secrets.HOST_IP }} '
          sudo mkdir -p /opt/cloudsecure && 
          sudo chown $USER:$USER /opt/cloudsecure && 
          cd /opt/cloudsecure && 
          echo "<html><body><h1>CloudSecure Deployed</h1><p>Time: $(date)</p></body></html>" > index.html && 
          echo "Installation successful at $(date)" > deployment.log && 
          echo "Success!"
          '